in ../../../builtins.maude
in ../imp-syntax.maude
in ../../state.maude

in imp-semantics-denotational

in ../imp-programs.maude

mod TEST is including IMP-SEMANTICS-DENOTATIONAL + IMP-PROGRAMS .  endm


---- Arithmetic
red appCPO( [[ 1 / 0 ]], x |-> 2 ) .
red appCPO( [[ ( 1 / 0 ) / 1 ]], x |-> 2 ) .
red appCPO( [[ 1 / ( 1 / 0 ) ]], x |-> 2 ) .
red appCPO( [[ ( 1 / 0 ) / ( 1 / 0 ) ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + 3 + ( 1 + 1 / 0 + 1) / ( 1 / 0 ) + 1 ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + 3 + ( 1 + 1 / 1 + 1) / ( 1 / 1 ) + 1 ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + x + ( x + 1 / 0 + 1) / ( x / 0 ) + 1 ]], x |-> 2 ) .

---- Boolean
red appCPO( [[ 1 <= 2 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 ]], x |-> 2 ) .
red appCPO( [[ x / 0 <= 1 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 / 0 ]], x |-> 2 ) .
red appCPO( [[ x / 0 <= 1 / 0 ]], x |-> 2 ) .

---- Statments
red appCPO( [[ y = 3 ; ]], x |-> 2 ) .
red appCPO( [[err]], x |-> 3 & err |-> 1 ) .
red appCPO( [[ x = 3 / 0 ; ]], x |-> 2 ) .
red appCPO( [[ x = 3 / 0 ; x = 10 ; ]], x |-> 2 ) .
red appCPO( [[ x = 3 ; x = 10 ; x = 12 ; ]], x |-> 2 ) .
red appCPO( [[ x = 3 ; x = 4 / 0 ; x = 100 ; ]], x |-> 2 ) .
red appCPO( [[ y = 3 ; x = 10 ; ]], x |-> 2 ) .

red appCPO( [[ if ( 0 <= 1 ) { x = 3 / 0 ; } else { x = 4 ; } ]], x |-> 2 ) .
red appCPO( [[ if ( 0 <= 1 / 0 ) { x = 3 ; } else { x = 4 ; } ]], x |-> 2 ) .
red appCPO( [[ if ( 0 <= 1 ) { x = 3 ; } else { x = 4 / 0 ; } ]], x |-> 2 ) .
red appCPO( [[ if ( 1 <= 0 ) { x = 3 ; } else { x = 4 ; } ]], x |-> 2 ) .
red appCPO( [[ if ( 1 <= 0 ) { x = 3 ; } else { x = 4 / 0 ; } ]], x |-> 2 ) .

red appCPO( [[ { x = 3 / 0 ; } ]], x |-> 2 ) .

--- While Loop
red appCPO( [[while (false) {} ]], x |-> 0 ) .
red appCPO( [[while ( 0 <= 0 / 0 ) {} ]], x |-> 0 ) .
red appCPO( [[while (x <= 5) { x = x + 1 ; } ]], x |-> 0 ) .

q
