in ../../../builtins.maude
in ../imp-syntax.maude
in ../../state.maude

in imp-semantics-denotational

in ../imp-programs.maude

mod TEST is including IMP-SEMANTICS-DENOTATIONAL + IMP-PROGRAMS .  endm


---- Arithmetic
red appCPO( [[ 1 / 0 ]], x |-> 2 ) .
red appCPO( [[ ( 1 / 0 ) / 1 ]], x |-> 2 ) .
red appCPO( [[ 1 / ( 1 / 0 ) ]], x |-> 2 ) .
red appCPO( [[ ( 1 / 0 ) / ( 1 / 0 ) ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + 3 + ( 1 + 1 / 0 + 1) / ( 1 / 0 ) + 1 ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + 3 + ( 1 + 1 / 1 + 1) / ( 1 / 1 ) + 1 ]], x |-> 2 ) .
red appCPO( [[ 1 + 2 + x + ( x + 1 / 0 + 1) / ( x / 0 ) + 1 ]], x |-> 2 ) .

---- Boolean
red appCPO( [[ 1 <= 2 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 ]], x |-> 2 ) .
red appCPO( [[ x / 0 <= 1 ]], x |-> 2 ) .
red appCPO( [[ x <= 1 / 0 ]], x |-> 2 ) .
red appCPO( [[ x / 0 <= 1 / 0 ]], x |-> 2 ) .

---- Statments
---red appCPO( [[ y = 3 ; ]], x |-> 2 ) .

q
